[package]
name = "ccp_vegas"
version = "0.1.0"
authors = ["Frank Cangialosi <frankc@csail.mit.edu>"]
edition = "2021"

[dependencies]
clap="4"
portus = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
